### ISSUE TITLE
(Vue) ユニットテストの準備・実装

### ISSUE THREAD

**Issue by myantyuWorld** [ayumi-sk2720/animal_healthcare_app#21]
# 以下の２観点を試しに実装し、レビューしてもらう
- コンポーネント
- axios絡むAPIリクエスト部分
基礎編：https://reffect.co.jp/vue/vue-jest-test/
axiosとコンポーネントを絡めたテスト：https://reffect.co.jp/vue/vue-mock-axios/

非同期処理自体に着目したテストについて
- [3 Ways To Mock Axios In Jest](https://vhudyma-blog.eu/3-ways-to-mock-axios-in-jest/)

**Comment by myantyuWorld** [comment]
[3 Ways To Mock Axios In Jest](https://vhudyma-blog.eu/3-ways-to-mock-axios-in-jest/)を参考にAPIのテストを実装してみた

正し、正常に動作できない状況を記録する
## 1. `Property 'mockResolvedValueOnce' does not exist on type ...`と表示される

以下のように変更すると、「２」の状態になった

```ts
- axios.get.mockResolvedValueOnce(petSummary);
+ (axios.get as any).mockResolvedValueOnce(petSummary);
```

## 2.

```
root@6b0e1e988d85:/vue_ts# npm run test:unit

> front@0.1.0 test:unit
> vue-cli-service test:unit

 FAIL  tests/unit/example.spec.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /vue_ts/node_modules/axios/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){import axios from './lib/axios.js';
                                                                                      ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      1 | import { shallowMount } from "@vue/test-utils";
      2 | import HelloWorld from "@/components/HelloWorld.vue";
    > 3 | import axios from "axios";
        | ^
      4 | import PetRepository from "@/apis/petRepository";
      5 |
      6 | jest.mock("axios");

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (tests/unit/example.spec.ts:3:1)
      at TestScheduler.scheduleTests (node_modules/@jest/core/build/TestScheduler.js:333:13)
      at runJest (node_modules/@jest/core/build/runJest.js:404:19)
      at _run10000 (node_modules/@jest/core/build/cli/index.js:320:7)
      at runCLI (node_modules/@jest/core/build/cli/index.js:173:3)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        12.216 s
Ran all test suites.
```

**Comment by myantyuWorld** [comment]
「２」について、以下の記事？
https://chaika.hatenablog.com/entry/2023/08/18/083000

**Comment by myantyuWorld** [comment]
# 3
上記記事を参考にして、`moduleMapper`に`axios`を指定すると、エラーメッセージが変わった

```
https://github.com/ayumi-sk2720/animal_healthcare_app/issues/21#issuecomment-1793729693
```

**Comment by myantyuWorld** [comment]
ひとまず、実行時にエラーが出なくなった。
ただ、正常にはテストできない状態なので、
せめて、`InfoPage.vue`のAPIリクエスト後のComponentの状態をテストしたい

**Comment by myantyuWorld** [comment]
@ayumi-sk2720 
未実装項目あるものの、レビューに備えてmainにマージする
`vue`フォルダ、はjavascriptでの実装になっていることから削除する（別PR）
